#!/bin/bash

echo "Welcome to <Company>'s HR Server!"
echo 
echo "All shared files are in the /shared folder, which should be linked in your home"
echo "directory. If you do not see this link, you can use the command 'cd /shared' to"
echo "access this folder."
echo 
echo "Please contact your supervisor if there are any issues with your account."
echo
echo "REMINDER: This data is confidential and should not be shared outside of company"
echo "servers."
echo
# $(tput cols) gets the # cols of the screen, but doesn't work for ssh entry
num=80 
str=$(printf "%${num}s")
echo ${str// /=}
echo